#!/bin/sh -e

# This is an OnChanged handler that can handle aktualir-lite .toml files.
# It copies the toml file to /etc/sota/conf.d/ and will restart aktualizr-lite

[ -z "$CONFIG_FILE" ] && (echo "No CONFIG_FILE specified"; exit 1)
cp $CONFIG_FILE /etc/sota/conf.d/

# If we take control of tags/apps, then we should try and remove from sota.toml
if grep -q "^\s*tags\s*=" $CONFIG_FILE 2>/dev/null ; then
	sed -e '/^\s*tags\s*=/ s/^#*/# MANAGED BY FIOCONFIG: /' -i /var/sota/sota.toml
fi

if grep -q "^\s*compose_apps\s*=" $CONFIG_FILE 2>/dev/null ; then
	sed -e '/^\s*compose_apps\s*=/ s/^#*/# MANAGED BY FIOCONFIG: /' -i /var/sota/sota.toml
fi

systemctl restart aktualizr-lite
