name: Lint
on:
  pull_request:

jobs:
  format:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - name: clone-code
        uses: actions/checkout@v4
      - name: golang-lint-ci
        uses: golangci/golangci-lint-action@v6
        with:
          args: "--build-tags vpn"
          version: v1.57
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'
      - name: clone-code
        uses: actions/checkout@v4
      - name: unit-tests
        run: go test -v ./...
